---
layout: post
title:  "Rmd的轉換測試"
date:   2016-10-03
categories: posts
output: html_document
---

最近因為工作需要，老闆好奇天氣資料與門店人流或銷售數字的關聯性，看了中央氣象局的[資料申購方法](http://e-service.cwb.gov.tw/wdps/cwb_fee.htm)，為了做個簡單的POC就得花錢買詳細的氣象資料，似乎太大張旗鼓了。還好，氣象局的[觀測資料查詢系統](http://e-service.cwb.gov.tw/HistoryDataQuery/index.jsp)可以提供手動查詢部分氣象站的資訊，觀察網頁的URL，只要進行日期的替換就可以做特定時間的查詢，而且產出的頁面也是整齊的表格，正好可以測試使用R爬取網頁資料的程序。


```{r echo=FALSE, message=FALSE, results='hide'}
# Load required packages
pkgs <- c('data.table', "plyr", "magrittr", 'reshape2', 'lubridate', 'stringr', 'ggplot2', 'dplyr', 'tidyr')
suppressPackageStartupMessages(lapply(pkgs, library, character.only=T, lib.loc = .libPaths()[1]))

library(RCurl)
library(XML)
library(httr)
library(scales)
library(plotly)

```

***

先做一次性的測試:  

```{r warning=FALSE, eval=TRUE}
# 先設定好站點編號
stationID <- '466930'

#----------------------------------------------#
# 撈取日報(逐小時的紀錄)
# 先設定好欄位名稱，撈取日期
tbNames <- c('ObsTime','StnPres','SeaPres','Temperature','TdDewPoint','RH','WS','WD','WSGust','WDGust','Precp','PrecpHour','SunShine','GloblRad','Visb')
fdate <- '2016-09-01'

cwbURL <- sprintf('http://e-service.cwb.gov.tw/HistoryDataQuery/DayDataController.do?command=viewMain&station=%s&stname=%s&datepicker=%s', stationID, '%25E8%2587%25BA%25E5%258C%2597', fdate)
weatherDate <- cwbURL %>%
  getURL() %>%
  htmlParse(., encoding = 'utf8', asText = TRUE) %>%
  readHTMLTable(header = TRUE) %$%
  MyTable %>%
  tbl_dt()

weatherDate %<>% filter(row.names(weatherDate) != 1)
weatherDate %<>% mutate_each(funs(as.numeric(as.character(.)))) %>% arrange(V1)
names(weatherDate) <- tbNames
weatherDate %<>% mutate(station = '竹子湖', cdate = fdate, ctime = (as.POSIXct(fdate)+hours(ObsTime-1)))

#----------------------------------------------#
# 撈取月報(逐日的紀錄)
# 先設定好欄位名稱，撈取日期
tbNames <- c('ObsTime','StnPres','SeaPres','StnPresMax','StnPresMaxTime','StnPresMin','StnPresMinTime','Temperature','TMax','TMaxTime','TMin','TMinTime','TdDewPoint','RH','RHMin','RHMinTime','WS','WD','WSGust','WDGust','WGustTime','Precp','PrecpHour','PrecpMax10','PrecpMax10Time','PrecpHrMax','PrecpHrMaxTime','SunShine','SunShineRate','GloblRad','VisbMean','EvapA')
fmonth <- '2016-09'

cwbURL <- sprintf('http://e-service.cwb.gov.tw/HistoryDataQuery/MonthDataController.do?command=viewMain&station=%s&stname=%s&datepicker=%s', stationID, '%25E7%25AB%25B9%25E5%25AD%2590%25E6%25B9%2596', fmonth)
weatherMonth <- cwbURL %>% 
  getURL() %>% 
  htmlParse(., encoding = 'utf8', asText = TRUE) %>% 
  readHTMLTable(header = TRUE) %$%
  MyTable %>% 
  tbl_dt()

weatherMonth %<>% filter(row.names(weatherMonth) != 1)
weatherMonth %<>% mutate_each(funs(as.numeric(as.character(.)))) %>% arrange(V1) 
names(weatherMonth) <- tbNames
weatherMonth %<>% mutate(station = '竹子湖', cdate = as.Date(str_c(fmonth, ObsTime, sep = '-')))

```

***

確認結果表都有抓到:
```{r , eval=TRUE}
# 日報(逐小時的紀錄)
weatherDate %>% head() %>% select(c(1:10)) %>% knitr::kable()

# 月報(逐日的紀錄)
weatherMonth %>% head() %>% select(c(1:10)) %>% knitr::kable()

```

***

